<#
.SYNOPSIS
    Creates the self-signed certificate that signs AlignPro's ClickOnce manifests during development.

.DESCRIPTION
    VSTO refuses to build without signed ClickOnce manifests. Visual Studio's wizard creates a
    temporary certificate silently when you make a project through the IDE; this script does the same
    thing explicitly, so a fresh clone can be built without opening Visual Studio first.

    It writes two files next to the add-in project, both gitignored because they are machine-local
    and one of them is a private key:

      AlignPro.AddIn_TemporaryKey.pfx   the certificate and its private key, no password
      Signing.props                     the MSBuild properties pointing at it

    This certificate is for development only. It is not trusted by anyone else's machine, so it is
    not the answer for shipping to colleagues - that needs a real code-signing certificate, which is
    a separate step (see README).

.PARAMETER Force
    Replace an existing certificate and props file rather than leaving them alone.

.EXAMPLE
    .\New-DevSigningCertificate.ps1
#>
[CmdletBinding()]
param(
    [switch] $Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$projectDir = Join-Path (Split-Path $PSScriptRoot -Parent) 'src\AlignPro.AddIn'
$pfxPath    = Join-Path $projectDir 'AlignPro.AddIn_TemporaryKey.pfx'
$propsPath  = Join-Path $projectDir 'Signing.props'
$subject    = 'CN=AlignPro Development'

if (-not (Test-Path $projectDir)) {
    throw "Add-in project directory not found at $projectDir."
}

if ((Test-Path $pfxPath) -and -not $Force) {
    Write-Host "Certificate already present at $pfxPath. Use -Force to replace it." -ForegroundColor Yellow
    return
}

Write-Host 'Creating a self-signed code-signing certificate...' -ForegroundColor Cyan
$cert = New-SelfSignedCertificate `
    -Type CodeSigningCert `
    -Subject $subject `
    -CertStoreLocation 'Cert:\CurrentUser\My' `
    -KeyUsage DigitalSignature `
    -KeyExportPolicy Exportable `
    -NotAfter (Get-Date).AddYears(5)

# Export-PfxCertificate insists on a password. VSTO temporary keys have none, so export through the
# certificate object instead, which accepts an empty one.
$bytes = $cert.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Pfx, '')
[System.IO.File]::WriteAllBytes($pfxPath, $bytes)

$props = @"
<Project>
  <!--
    Generated by tools/New-DevSigningCertificate.ps1 - do not commit. The thumbprint is specific to
    the certificate on this machine, which is why these properties live here rather than in the
    .csproj. Regenerate with: .\tools\New-DevSigningCertificate.ps1 -Force
  -->
  <PropertyGroup>
    <SignManifests>true</SignManifests>
    <ManifestKeyFile>AlignPro.AddIn_TemporaryKey.pfx</ManifestKeyFile>
    <ManifestCertificateThumbprint>$($cert.Thumbprint)</ManifestCertificateThumbprint>
  </PropertyGroup>
</Project>
"@

Set-Content -Path $propsPath -Value $props -Encoding UTF8

Write-Host ''
Write-Host 'Done.' -ForegroundColor Green
Write-Host ("  subject:    {0}" -f $subject)
Write-Host ("  thumbprint: {0}" -f $cert.Thumbprint)
Write-Host ("  expires:    {0:yyyy-MM-dd}" -f $cert.NotAfter)
Write-Host ("  pfx:        {0}" -f $pfxPath)
Write-Host ("  props:      {0}" -f $propsPath)
Write-Host ''
Write-Host 'Both files are gitignored. Development only - not trusted on any other machine.' -ForegroundColor DarkGray
