<#
.SYNOPSIS
    Builds the AlignPro MSI.

.DESCRIPTION
    Packages an already-built Release into a per-user MSI: no administrator rights to install, an
    entry in Add/Remove Programs, and deployable to managed machines through Intune or Group Policy.

    This is the managed-deployment path, not the one a person downloads. An unsigned MSI is warned
    about by SmartScreen on every release - reputation for an unsigned file starts at zero for each
    new build, and a self-signed certificate counts as no signature - so the download route is the zip
    from New-Package.ps1, which install.ps1 fetches without the browser ever being involved. Intune and
    Group Policy install without any of that applying, which is why the MSI is still worth building.

    The public key that grants trust is extracted here, from the signed manifest in the build output,
    and written to installer/PublicKey.wxi. Generating it rather than committing it means the trust
    entry cannot drift from the build it belongs to.

    Requires the WiX tool:  dotnet tool install --global wix

.PARAMETER Version
    Version for the MSI, e.g. 1.0.0.

.PARAMETER Configuration
    Build configuration to package. Defaults to Release.

.EXAMPLE
    .\New-Installer.ps1 -Version 1.0.0
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [ValidatePattern('^\d+\.\d+\.\d+$')]
    [string] $Version,

    [string] $Configuration = 'Release'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$projectRoot = Split-Path $PSScriptRoot -Parent
$binDir = Join-Path $projectRoot "src\AlignPro.AddIn\bin\$Configuration"
$installerDir = Join-Path $projectRoot 'installer'
$deck = Join-Path $projectRoot 'sample\AlignPro-Sample.pptx'
$outputDir = Join-Path $projectRoot 'dist'

# --- wix -----------------------------------------------------------------------------------------
$wix = Get-Command wix -ErrorAction SilentlyContinue
if (-not $wix) {
    $candidate = Join-Path $env:USERPROFILE '.dotnet\tools\wix.exe'
    if (Test-Path $candidate) { $wix = $candidate } else {
        throw "WiX was not found. Install it with:  dotnet tool install --global wix"
    }
}
else { $wix = $wix.Source }

# --- inputs --------------------------------------------------------------------------------------
$payload = @(
    'AlignPro.AddIn.dll'
    'AlignPro.AddIn.dll.manifest'
    'AlignPro.AddIn.vsto'
    'AlignPro.Geometry.dll'
    'Microsoft.Office.Tools.Common.v4.0.Utilities.dll'
)
$missing = $payload | Where-Object { -not (Test-Path (Join-Path $binDir $_)) }
if ($missing) { throw "Build output is missing from '$binDir': $($missing -join ', '). Build $Configuration first." }
if (-not (Test-Path $deck)) { throw "The sample deck is missing from '$deck'. Run tools\New-SampleDeck.ps1 first." }

# --- the trust key -------------------------------------------------------------------------------
# Read straight out of the manifest that is about to be packaged, so the two cannot disagree.
[xml] $manifestXml = Get-Content (Join-Path $binDir 'AlignPro.AddIn.vsto') -Raw
$ns = New-Object System.Xml.XmlNamespaceManager($manifestXml.NameTable)
$ns.AddNamespace('ds', 'http://www.w3.org/2000/09/xmldsig#')
$rsa = $manifestXml.SelectSingleNode('//ds:Signature/ds:KeyInfo/ds:KeyValue/ds:RSAKeyValue', $ns)
if (-not $rsa) { throw 'The manifest carries no signature public key - was it signed?' }

$publicKey = '<RSAKeyValue><Modulus>' + $rsa.Modulus + '</Modulus><Exponent>' + $rsa.Exponent + '</Exponent></RSAKeyValue>'

# Written raw, NOT XML-escaped. <?define?> is a processing instruction and its content is not parsed
# as XML, so an escaped value is never unescaped and reaches the registry as "&lt;RSAKeyValue&gt;..."
# - which VSTO does not recognise, and which fails silently as a refusal to load.
$wxi = @"
<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by tools/New-Installer.ps1 from the signed manifest. Do not edit, and do not commit:
  it belongs to one particular build, signed by one particular certificate.
-->
<Include>
  <?define AlignProPublicKey = "$publicKey" ?>
</Include>
"@
Set-Content -Path (Join-Path $installerDir 'PublicKey.wxi') -Value $wxi -Encoding UTF8
Write-Host "  trust key extracted from the signed manifest" -ForegroundColor DarkGray

# --- build ---------------------------------------------------------------------------------------
if (-not (Test-Path $outputDir)) { New-Item -ItemType Directory -Path $outputDir -Force | Out-Null }
$msi = Join-Path $outputDir "AlignPro-$Version.msi"

Write-Host ''
Write-Host "Building $msi" -ForegroundColor Cyan
& $wix build (Join-Path $installerDir 'AlignPro.wxs') `
    -define "Version=$Version" `
    -define "BinDir=$binDir" `
    -define "SampleDeck=$deck" `
    -out $msi
if ($LASTEXITCODE -ne 0) { throw 'WiX build failed.' }

$size = (Get-Item $msi).Length
Write-Host ''
Write-Host "Packaged: $msi" -ForegroundColor Green
Write-Host ("  {0:N0} KB" -f ($size / 1KB))
Write-Host ''
Write-Host 'Per-user install: no administrator rights, appears in Add/Remove Programs.' -ForegroundColor DarkGray
Write-Host ''
